
<?php echo "Reto 3";?>

<?php $products = $this->getProducts();?>
<?php $baseUrl = $this->getBaseUrl();?>

<?php foreach($products as $product):?>

<p>
	<?php if ($product->isSalable()):?>
	<?php $qty = $this->getQty($product)?>
    	<?php if ($qty<=10 || $qty>=50):?>
    	    <b><?php echo $product->getName()?></b>
        	$<?php echo $product->getPrice()?>
        	#<?php echo $qty?>
        	<img src="<?php echo $baseUrl.$product->getImage()?>">
        	
        	<?php
        	$productid = $product->getId();
            $formKey = Mage::getSingleton('core/session')->getFormKey();?>
            
            <form action="/checkout/cart/add/product/<?php echo $productid; ?>" method="post">
                Session<input type="text" name="form_key" value="<?php echo $formKey; ?>" />
                <input type="text" name="qty"> QTY
                <input disabled type="submit" value="Add to CAr" />
            </form>
        	
    	<?php endif;?>
	<?php endif;?>
</p>

<?php endforeach;?>