<?php
echo "Reto 3";

$products = Mage::getModel('catalog/product')->getCollection()->addAttributeToSelect('*');
$baseUrl = Mage::getBaseUrl('media') . 'catalog/product/';

foreach($products as $product):?>

<p>
	<?php if ($product->isSalable()):?>
	<?php $qty = (int)Mage::getModel('cataloginventory/stock_item')->loadByProduct($product)->getQty();?>
    	<?php if ($qty<=10 || $qty>=50):?>
    	    <b><?php echo $product->getName()?></b>
        	$<?php echo $product->getPrice()?>
        	#<?php echo $qty?>
        	<img src="<?php echo $baseUrl.$product->getImage()?>">
        	<?php #getthumbnail()?>
    	<?php endif;?>
	<?php endif;?>
</p>

<?php endforeach;?>